templates:
  tv:
    transmission:
      host: localhost
      port: 9091
      username: pi
      password: raspberry
    clean_transmission:
      host: localhost
      port: 9091
      username: pi
      password: raspberry
      min_ratio: 1
    set:
      path: "~/xbmc_media/Downloads/complete/tv/{{ series_name }}/Season {{ series_season }}"
    exists_series:
      - ~/xbmc_media/Downloads/complete/tv/
      - ~/xbmc_media/TV
    series:
      webrip:
        - House of Cards (2013):
            begin: S02E01
      hdtv:
        - American Horror Story
        - Arrow
        - Archer (2009)
        - Black Mirror:
            begin: S03E01
        - Community
        - Chozen
        - Doctor Who (2005)
        - Elementary
        - Falling Skies
        - Helix
        - Hell on Wheels
        - Game of Thrones
        - Grimm
        - Hart of Dixie
        - Legit (2013)
        - Louie
        - Marvel's Agents of S.H.I.E.L.D.:
            set:
              series_name: Marvel's Agents of SHIELD
        - Modern Family
        - New Girl
        - Parks and Recreation
        - Portlandia
        - Revolution
        - Sherlock
        - The After
        - The Big Bang Theory
        - The Following
        - The Good Wife
        - The Walking Dead
        - Under the Dome
        - Wilfred (AU? US?):
            set:
              series_name: Wilfred (US)

tasks:
  showrss:
    rss: http://showrss.info/rss.php?user_id=71878&hd=0&proper=1
    template: tv
