presets:
  tv:
    transmission:
      host: localhost
      port: 9091
      username: pi
      password: raspberry
      removewhendone: Yes
    set:
      path: "~/downloads/complete/tv/{{ series_name }}/Season {{ series_season }}"
    exists_series:
      - ~/downloads/complete/tv/
      - ~/tv
    series:
      hdtv:
        - American Horror Story
        - Arrested Development:
            watched: S03E13
        - Archer (2009)
        - Black Mirror:
            watched: S02E03
        - Community:
            watched: S04E13
        - Dexter
        - Doctor Who (2005)
        - Elementary
        - Falling Skies
        - Defiance
        - Game of Thrones
        - Glee
        - Grimm
        - Hart of Dixie
        - House of Cards (2013):
            watched: S01E13
        - Legit (2013)
        - Louie
        - Modern Family
        - New Girl
        - Parks and Recreation
        - Portlandia
        - Revolution
        - The Big Bang Theory
        - The Following
        - The Good Wife
        - The Walking Dead
        - Touch (2012)
        - Wilfred (AU? US?):
            set:
              series_name: Wilfred (US)

tasks:
  showrss:
    rss: http://showrss.karmorra.info/rss.php?user_id=71878&hd=0&proper=1
    preset: tv
