ZSH=$HOME/.oh-my-zsh
ZSH_CUSTOM=$HOME/.dotfiles/zsh/custom

ZSH_THEME="robbyrussell"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(zsh_reload z git sublime symfony2 composer vagrant)

source $ZSH/oh-my-zsh.sh

# Disable autocorrect
unsetopt correct_all

# Don't ask for confirmation for `rm *' or `rm path/*'
setopt rm_star_silent

# Customize to your needs...
export PATH="$PATH:$HOME/.dotfiles/bin:$HOME/.rvm/bin"

# Aliases
alias v='vagrant';
alias gdc='git diff --cached'

LC_CTYPE=en_US.UTF-8
LC_ALL=en_US.UTF-8

# in vagrant, the git status indicator is unacceptably slow so we disable it
function git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}${ZSH_THEME_GIT_PROMPT_CLEAN}${ZSH_THEME_GIT_PROMPT_SUFFIX}"
}

if [ $(whoami) = 'vagrant' ]; then
  cd /vagrant
fi

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
