ZSH=$HOME/.oh-my-zsh
DOT=$HOME/.dotfiles
ZSH_CUSTOM=$DOT/zsh/custom

ZSH_THEME="robbyrussell"
DISABLE_AUTO_UPDATE="false"    # weekly auto-update
COMPLETION_WAITING_DOTS="true" # red dots are displayed while waiting for completion

# Active plugins (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(zsh_reload z extract git sublime symfony2 composer vagrant brew)

source $ZSH/oh-my-zsh.sh

unsetopt correct_all  # Disable autocorrect
setopt rm_star_silent # Don't ask for confirmation for `rm *' or `rm path/*'

# All of our zsh files
typeset -U config_files
config_files=($DOT/**/*.zsh)

# Load the path files
for file in ${(M)config_files:#*/path.zsh}; do source $file; done

# Load everything but the path and install files
for file in ${${config_files:#*/path.zsh}:#*/install.zsh}; do source $file; done

eval $(thefuck --alias fu)
